name: Add Release Notes to a Release PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
    branches:
      - releases/*

jobs:
  changelog:
    name: Release Notes
    runs-on: ubuntu-latest

    steps:
      - uses: daytime-em/changelog-on-pr@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: breaking,updates,fixes,deprecated
